name: Check Python Versions

on: [push]

jobs:
  check-python-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # You can replace this with any version you want to check
      - name: Check Python version
        run: python --version
      - name: Check installed Python versions
        run: |
          for version in $(ls /opt/python/); do
            echo "Available Python version: $version"
          done
